### ISSUE TITLE
Error on running rbtc

### ISSUE THREAD

**Issue by JsonSam** [hstove/rbtc_arbitrage#7]
$ rbtc
/home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>': uninitialized constant ActiveSupport::Autoload (NameError)
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/number_helper.rb:2:in`module:ActiveSupport'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/number_helper.rb:1:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/core_ext/numeric/conversions.rb:2:in`require'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/core_ext/numeric.rb:3:in`require'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:2:in`require'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:1:in`each'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:1:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/bitstamp-0.3.0/lib/bitstamp.rb:1:in`require'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/bitstamp-0.3.0/lib/bitstamp.rb:1:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/rbtc_arbitrage-1.4.4/lib/rbtc_arbitrage.rb:4:in`require'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/rbtc_arbitrage-1.4.4/lib/rbtc_arbitrage.rb:4:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/rbtc_arbitrage-1.4.4/bin/rbtc:4:in`require'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/gems/rbtc_arbitrage-1.4.4/bin/rbtc:4:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/bin/rbtc:23:in`load'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/bin/rbtc:23:in `<main>'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/bin/ruby_executable_hooks:15:in`eval'
    from /home/user/.rvm/gems/ruby-2.1.0@demo/bin/ruby_executable_hooks:15:in `<main>'

**Comment by DestyNova** [comment]
Adding that require line before `require 'rbtc_arbitrage'` works here. Well, it gets me to the next error about httparty and the JSON lib :cactus:
